version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: always
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    restart: always
  caddy:
    image: caddy:2.8.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticfiles:/srv/staticfiles
      - ./media:/srv/media
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
  caddy_data:
  caddy_config: